# Generated by Django 2.0.2 on 2018-02-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingProductBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=64)),
                ('fin_co_no', models.CharField(max_length=64)),
                ('kor_co_nm', models.CharField(max_length=64)),
                ('fin_prdt_cd', models.CharField(max_length=64)),
                ('fin_prdt_nm', models.CharField(max_length=64)),
                ('join_way', models.CharField(max_length=64)),
                ('mtrt_int', models.CharField(max_length=256)),
                ('spcl_cnd', models.CharField(max_length=256)),
                ('join_deny', models.CharField(max_length=64)),
                ('join_member', models.CharField(max_length=256)),
                ('etc_note', models.CharField(max_length=256)),
                ('max_limit', models.IntegerField(null=True)),
                ('dcls_strt_day', models.CharField(max_length=64)),
                ('dcls_end_day', models.CharField(max_length=64, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'saving_product_base',
            },
        ),
        migrations.CreateModel(
            name='SavingProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=64)),
                ('fin_co_no', models.CharField(max_length=64)),
                ('fin_prdt_cd', models.CharField(max_length=64)),
                ('intr_rate_type', models.CharField(max_length=64)),
                ('intr_rate_type_nm', models.CharField(max_length=64)),
                ('rsrv_type', models.CharField(max_length=64)),
                ('rsrv_type_nm', models.CharField(max_length=64)),
                ('save_trm', models.CharField(max_length=64)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'saving_product_option',
            },
        ),
    ]
