# Generated by Django 2.0.2 on 2018-02-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingproductbase',
            name='top_fin_grp_no',
            field=models.CharField(default='020000', max_length=64),
            preserve_default=False,
        ),
    ]
