# Generated by Django 2.0.2 on 2018-03-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0002_savingproductbase_top_fin_grp_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='savingproductbase',
            table='saving_products_base',
        ),
        migrations.AlterModelTable(
            name='savingproductoption',
            table='saving_products_option',
        ),
    ]
