# Generated by Django 2.0.2 on 2018-03-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('saving', '0003_auto_20180307_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingProductBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saving_product_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving.SavingProductBase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'saving_products_bookmark',
            },
        ),
    ]
