# Generated by Django 2.0.2 on 2018-06-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0004_savingproductbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproductbase',
            name='max_limit',
            field=models.BigIntegerField(null=True),
        ),
    ]
