# Generated by Django 2.0.2 on 2018-03-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=64)),
                ('fin_co_no', models.CharField(max_length=64)),
                ('kor_co_nm', models.CharField(max_length=64)),
                ('dcls_chrg_man', models.CharField(max_length=256)),
                ('homp_url', models.CharField(max_length=256)),
                ('cal_tel', models.CharField(max_length=64)),
                ('top_fin_grp_no', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_base',
            },
        ),
        migrations.CreateModel(
            name='CompanyOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=64)),
                ('fin_co_no', models.CharField(max_length=64)),
                ('area_cd', models.CharField(max_length=64)),
                ('area_nm', models.CharField(max_length=64)),
                ('exis_yn', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_option',
            },
        ),
    ]
