# Generated by Django 2.0.2 on 2018-02-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saving', '0002_savingproductbase_top_fin_grp_no'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_period', models.CharField(max_length=64)),
                ('payment_date', models.CharField(max_length=64, null=True)),
                ('payment_amount', models.IntegerField(default=0, null=True)),
                ('rsrv_type', models.CharField(max_length=64)),
                ('intr_rate_type', models.CharField(max_length=64)),
                ('intr_rate', models.FloatField(null=True)),
                ('prime_rate', models.FloatField(null=True)),
                ('now_amount', models.IntegerField(default=0)),
                ('max_amount', models.IntegerField(null=True)),
                ('join_date', models.CharField(max_length=64)),
                ('expiry_date', models.CharField(max_length=64)),
                ('is_expired', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saving_product_base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving.SavingProductBase')),
                ('saving_product_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saving.SavingProductOption')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'bankbooks',
            },
        ),
    ]
