# Generated by Django 2.0.2 on 2018-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbook',
            name='account_number',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
