# Generated by Django 2.0.2 on 2018-03-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankbook', '0002_bankbook_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankbook',
            old_name='saving_product_base_id',
            new_name='saving_product_base',
        ),
        migrations.RenameField(
            model_name='bankbook',
            old_name='saving_product_option_id',
            new_name='saving_product_option',
        ),
        migrations.RenameField(
            model_name='bankbook',
            old_name='user_id',
            new_name='user',
        ),
    ]
