# Generated by Django 2.0.2 on 2018-03-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='bankbook_id',
            new_name='bankbook',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='user_id',
            new_name='user',
        ),
    ]
