# Generated by Django 2.0.2 on 2018-07-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('picture_url', models.CharField(max_length=255, null=True)),
                ('sns_type', models.CharField(max_length=50, null=True)),
                ('sns_id', models.CharField(max_length=255, null=True)),
                ('sns_access_token', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('G', 'Guest')], default='G', max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('sns_type', 'sns_id')},
        ),
    ]
